version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: deployment/docker/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/galileo_development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./web:/app
      - ./analyzers:/analyzers

  workers:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.analyzers
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/galileo_development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./analyzers:/app
      - ./web:/web

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: galileo_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: